"""Template Jinja yang dibundel agar selalu tersedia di Vercel Function.
File ini dibuat otomatis oleh build_template_bundle.py.
"""

TEMPLATES = {'admin/base_admin.html': '<!doctype html>\n'
                          '<html lang="id">\n'
                          '<head>\n'
                          '    <meta charset="utf-8">\n'
                          '    <meta name="viewport" content="width=device-width, '
                          'initial-scale=1">\n'
                          '    <title>{% block title %}Admin Jenny{% endblock %}</title>\n'
                          '    <link rel="preconnect" href="https://fonts.googleapis.com">\n'
                          '    <link rel="preconnect" href="https://fonts.gstatic.com" '
                          'crossorigin>\n'
                          '    <link '
                          'href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" '
                          'rel="stylesheet">\n'
                          '    <link rel="stylesheet" '
                          'href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">\n'
                          '    <link rel="stylesheet" href="{{ url_for(\'static\', '
                          'filename=\'css/admin.css\') }}">\n'
                          '</head>\n'
                          '<body class="admin-body">\n'
                          '    <aside class="admin-sidebar" id="admin-sidebar">\n'
                          '        <a class="admin-brand" href="{{ url_for(\'admin.dashboard\') '
                          '}}">Jenny.</a>\n'
                          '        <p class="admin-caption">Portfolio Manager</p>\n'
                          '        <nav class="admin-nav">\n'
                          '            <a href="{{ url_for(\'admin.dashboard\') }}" class="{{ '
                          '\'active\' if request.endpoint == \'admin.dashboard\' else \'\' }}"><i '
                          'class="bi bi-grid"></i> Dashboard</a>\n'
                          '            <a href="{{ url_for(\'profile.edit\') }}" class="{{ '
                          '\'active\' if request.blueprint == \'profile\' else \'\' }}"><i '
                          'class="bi bi-person"></i> Profil</a>\n'
                          '            <a href="{{ url_for(\'skills_admin.index\') }}" class="{{ '
                          '\'active\' if request.blueprint == \'skills_admin\' else \'\' }}"><i '
                          'class="bi bi-stars"></i> Keahlian</a>\n'
                          '            <a href="{{ url_for(\'experiences_admin.index\') }}" '
                          'class="{{ \'active\' if request.blueprint == \'experiences_admin\' else '
                          '\'\' }}"><i class="bi bi-briefcase"></i> Pengalaman</a>\n'
                          '            <a href="{{ url_for(\'projects_admin.index\') }}" class="{{ '
                          '\'active\' if request.blueprint == \'projects_admin\' else \'\' }}"><i '
                          'class="bi bi-folder"></i> Proyek</a>\n'
                          '            <a href="{{ url_for(\'admin.messages\') }}" class="{{ '
                          '\'active\' if request.endpoint == \'admin.messages\' else \'\' }}"><i '
                          'class="bi bi-envelope"></i> Pesan</a>\n'
                          '        </nav>\n'
                          '        <div class="sidebar-bottom">\n'
                          '            <a href="{{ url_for(\'main.home\') }}" target="_blank"><i '
                          'class="bi bi-box-arrow-up-right"></i> Lihat Website</a>\n'
                          '            <form action="{{ url_for(\'auth.logout\') }}" '
                          'method="post">\n'
                          '                <input type="hidden" name="csrf_token" value="{{ '
                          'csrf_token() }}">\n'
                          '                <button type="submit"><i class="bi '
                          'bi-box-arrow-left"></i> Keluar</button>\n'
                          '            </form>\n'
                          '        </div>\n'
                          '    </aside>\n'
                          '\n'
                          '    <div class="admin-shell">\n'
                          '        <header class="admin-topbar">\n'
                          '            <button type="button" class="sidebar-toggle" '
                          'aria-label="Buka menu"><i class="bi bi-list"></i></button>\n'
                          '            <div>\n'
                          '                <p>Selamat datang,</p>\n'
                          '                <strong>{{ current_user.name }}</strong>\n'
                          '            </div>\n'
                          '        </header>\n'
                          '        <main class="admin-main">\n'
                          '            <div class="admin-flashes">\n'
                          '                {% with messages = '
                          'get_flashed_messages(with_categories=true) %}\n'
                          '                    {% for category, message in messages %}\n'
                          '                        <div class="admin-alert alert-{{ category '
                          '}}">{{ message }}</div>\n'
                          '                    {% endfor %}\n'
                          '                {% endwith %}\n'
                          '            </div>\n'
                          '            {% block content %}{% endblock %}\n'
                          '        </main>\n'
                          '    </div>\n'
                          '    <script src="{{ url_for(\'static\', filename=\'js/admin.js\') }}" '
                          'defer></script>\n'
                          '    {% block scripts %}{% endblock %}\n'
                          '</body>\n'
                          '</html>\n',
 'admin/dashboard.html': '{% extends "admin/base_admin.html" %}\n'
                         '{% block title %}Dashboard | Admin Jenny{% endblock %}\n'
                         '{% block content %}\n'
                         '<div class="page-heading">\n'
                         '    <div><span class="eyebrow">Ringkasan</span><h1>Dashboard</h1></div>\n'
                         '    <a class="admin-button" href="{{ url_for(\'main.home\') }}" '
                         'target="_blank"><i class="bi bi-eye"></i> Preview Website</a>\n'
                         '</div>\n'
                         '<div class="metric-grid">\n'
                         '    <article><span class="metric-icon"><i class="bi '
                         'bi-stars"></i></span><div><strong>{{ metrics.skills '
                         '}}</strong><p>Keahlian</p></div></article>\n'
                         '    <article><span class="metric-icon"><i class="bi '
                         'bi-briefcase"></i></span><div><strong>{{ metrics.experiences '
                         '}}</strong><p>Pengalaman</p></div></article>\n'
                         '    <article><span class="metric-icon"><i class="bi '
                         'bi-folder"></i></span><div><strong>{{ metrics.projects '
                         '}}</strong><p>Proyek</p></div></article>\n'
                         '    <article><span class="metric-icon"><i class="bi '
                         'bi-envelope"></i></span><div><strong>{{ metrics.unread_messages '
                         '}}</strong><p>Pesan Belum Dibaca</p></div></article>\n'
                         '</div>\n'
                         '<div class="dashboard-grid">\n'
                         '    <section class="admin-panel">\n'
                         '        <div class="panel-header"><div><h2>Pesan Terbaru</h2><p>Pesan '
                         'yang baru masuk dari form kontak.</p></div><a href="{{ '
                         'url_for(\'admin.messages\') }}">Lihat semua</a></div>\n'
                         '        <div class="message-list compact">\n'
                         '            {% for message in latest_messages %}\n'
                         '                <article class="message-row {{ \'\' if message.is_read '
                         'else \'unread\' }}">\n'
                         '                    <span class="avatar">{{ message.name[:1]|upper '
                         '}}</span>\n'
                         '                    <div><strong>{{ message.name }}</strong><p>{{ '
                         'message.subject }}</p></div>\n'
                         "                    <time>{{ message.created_at.strftime('%d/%m/%Y') "
                         '}}</time>\n'
                         '                </article>\n'
                         '            {% else %}<p class="empty-state">Belum ada pesan '
                         'masuk.</p>{% endfor %}\n'
                         '        </div>\n'
                         '    </section>\n'
                         '    <section class="admin-panel quick-panel">\n'
                         '        <div class="panel-header"><div><h2>Aksi Cepat</h2><p>Perbarui '
                         'bagian utama website.</p></div></div>\n'
                         '        <a href="{{ url_for(\'profile.edit\') }}"><i class="bi '
                         'bi-person"></i><span><strong>Edit Profil</strong><small>Nama, foto, bio, '
                         'dan sosial media</small></span></a>\n'
                         '        <a href="{{ url_for(\'projects_admin.index\') }}"><i class="bi '
                         'bi-plus-circle"></i><span><strong>Tambah '
                         'Proyek</strong><small>Publikasikan karya terbaru</small></span></a>\n'
                         '        <a href="{{ url_for(\'experiences_admin.index\') }}"><i '
                         'class="bi bi-briefcase"></i><span><strong>Tambah '
                         'Pengalaman</strong><small>Perbarui perjalanan '
                         'profesional</small></span></a>\n'
                         '    </section>\n'
                         '</div>\n'
                         '{% endblock %}\n',
 'admin/experiences.html': '{% extends "admin/base_admin.html" %}\n'
                           '{% block title %}Pengalaman | Admin Jenny{% endblock %}\n'
                           '{% block content %}\n'
                           '<div class="page-heading"><div><span '
                           'class="eyebrow">Timeline</span><h1>Pengalaman</h1></div></div>\n'
                           '<section class="admin-panel form-panel">\n'
                           '    <div class="form-section-title"><h2>Tambah Pengalaman</h2></div>\n'
                           '    <form method="post" enctype="multipart/form-data" class="form-grid '
                           'two-columns compact-form">\n'
                           '        <input type="hidden" name="csrf_token" value="{{ csrf_token() '
                           '}}">\n'
                           '        <label>Perusahaan / Organisasi<input type="text" '
                           'name="company" required></label>\n'
                           '        <label>Posisi / Peran<input type="text" name="role" '
                           'required></label>\n'
                           '        <label>Tahun Mulai<input type="text" name="start_year" '
                           'placeholder="2024" required></label>\n'
                           '        <label>Tahun Selesai<input type="text" name="end_year" '
                           'value="Present"></label>\n'
                           '        <label>Ikon<input type="text" name="icon" '
                           'value="bi-flower1"></label>\n'
                           '        <label>Urutan<input type="number" name="sort_order" '
                           'value="0"></label>\n'
                           '        <label class="full-column">Deskripsi<textarea '
                           'name="description" rows="4"></textarea></label>\n'
                           '        <label class="full-column">Gambar<input type="file" '
                           'name="image" accept="image/png,image/jpeg,image/webp"></label>\n'
                           '        <div class="form-actions"><button class="admin-button" '
                           'type="submit"><i class="bi bi-plus"></i> Tambahkan</button></div>\n'
                           '    </form>\n'
                           '</section>\n'
                           '<div class="admin-list-grid one-column">\n'
                           '    {% for experience in experiences %}\n'
                           '    <article class="admin-panel experience-admin-card">\n'
                           '        <div class="admin-thumb">{% if experience.image_url %}<img '
                           'src="{{ experience.image_url }}" alt="{{ experience.company }}">{% '
                           'else %}<i class="bi bi-image"></i>{% endif %}</div>\n'
                           '        <div class="experience-admin-info"><span>{{ '
                           'experience.start_year }} — {{ experience.end_year }}</span><h3>{{ '
                           'experience.company }}</h3><h4>{{ experience.role }}</h4><p>{{ '
                           'experience.description }}</p></div>\n'
                           '        <details><summary>Edit</summary>\n'
                           '            <form method="post" enctype="multipart/form-data" '
                           'action="{{ url_for(\'experiences_admin.update\', '
                           'experience_id=experience.id) }}" class="form-grid two-columns '
                           'compact-form">\n'
                           '                <input type="hidden" name="csrf_token" value="{{ '
                           'csrf_token() }}">\n'
                           '                <label>Perusahaan<input type="text" name="company" '
                           'value="{{ experience.company }}" required></label>\n'
                           '                <label>Posisi<input type="text" name="role" value="{{ '
                           'experience.role }}" required></label>\n'
                           '                <label>Tahun Mulai<input type="text" name="start_year" '
                           'value="{{ experience.start_year }}" required></label>\n'
                           '                <label>Tahun Selesai<input type="text" name="end_year" '
                           'value="{{ experience.end_year }}"></label>\n'
                           '                <label>Ikon<input type="text" name="icon" value="{{ '
                           'experience.icon }}"></label>\n'
                           '                <label>Urutan<input type="number" name="sort_order" '
                           'value="{{ experience.sort_order }}"></label>\n'
                           '                <label class="full-column">Deskripsi<textarea '
                           'name="description" rows="4">{{ experience.description '
                           '}}</textarea></label>\n'
                           '                <label class="full-column">Ganti gambar<input '
                           'type="file" name="image" '
                           'accept="image/png,image/jpeg,image/webp"></label>\n'
                           '                <div class="form-actions"><button class="admin-button '
                           'small" type="submit">Simpan</button></div>\n'
                           '            </form>\n'
                           '        </details>\n'
                           '        <form method="post" action="{{ '
                           'url_for(\'experiences_admin.delete\', experience_id=experience.id) }}" '
                           'data-confirm="Hapus pengalaman ini?">\n'
                           '            <input type="hidden" name="csrf_token" value="{{ '
                           'csrf_token() }}"><button class="danger-button" type="submit"><i '
                           'class="bi bi-trash"></i> Hapus</button>\n'
                           '        </form>\n'
                           '    </article>\n'
                           '    {% else %}<p class="empty-state">Belum ada pengalaman.</p>{% '
                           'endfor %}\n'
                           '</div>\n'
                           '{% endblock %}\n',
 'admin/messages.html': '{% extends "admin/base_admin.html" %}\n'
                        '{% block title %}Pesan | Admin Jenny{% endblock %}\n'
                        '{% block content %}\n'
                        '<div class="page-heading"><div><span '
                        'class="eyebrow">Inbox</span><h1>Pesan Kontak</h1></div></div>\n'
                        '<div class="message-list full-list">\n'
                        '    {% for message in messages %}\n'
                        '    <article class="admin-panel message-card {{ \'\' if message.is_read '
                        'else \'unread\' }}">\n'
                        '        <div class="message-card-top"><span class="avatar">{{ '
                        'message.name[:1]|upper }}</span><div><h3>{{ message.name }}</h3><a '
                        'href="mailto:{{ message.email }}">{{ message.email }}</a></div><time>{{ '
                        "message.created_at.strftime('%d %b %Y, %H:%M') }}</time></div>\n"
                        '        <div class="message-subject"><strong>{{ message.subject '
                        '}}</strong><span class="status-chip">Email: {{ message.email_status '
                        '}}</span></div>\n'
                        '        <p class="message-content">{{ message.message }}</p>\n'
                        '        <div class="message-actions">\n'
                        '            <form method="post" action="{{ '
                        'url_for(\'admin.toggle_message_read\', message_id=message.id) }}"><input '
                        'type="hidden" name="csrf_token" value="{{ csrf_token() }}"><button '
                        'class="secondary-button" type="submit"><i class="bi {{ \'bi-envelope\' if '
                        'message.is_read else \'bi-envelope-open\' }}"></i> {{ \'Tandai belum '
                        "dibaca' if message.is_read else 'Tandai dibaca' }}</button></form>\n"
                        '            <form method="post" action="{{ '
                        'url_for(\'admin.delete_message\', message_id=message.id) }}" '
                        'data-confirm="Hapus pesan ini?"><input type="hidden" name="csrf_token" '
                        'value="{{ csrf_token() }}"><button class="danger-button" type="submit"><i '
                        'class="bi bi-trash"></i> Hapus</button></form>\n'
                        '        </div>\n'
                        '    </article>\n'
                        '    {% else %}<p class="empty-state">Belum ada pesan.</p>{% endfor %}\n'
                        '</div>\n'
                        '{% endblock %}\n',
 'admin/profile.html': '{% extends "admin/base_admin.html" %}\n'
                       '{% block title %}Profil | Admin Jenny{% endblock %}\n'
                       '{% block content %}\n'
                       '<div class="page-heading"><div><span class="eyebrow">Konten '
                       'utama</span><h1>Profil</h1></div></div>\n'
                       '<form class="admin-panel form-panel" method="post" '
                       'enctype="multipart/form-data">\n'
                       '    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">\n'
                       '    <div class="form-section-title"><h2>Identitas Utama</h2></div>\n'
                       '    <div class="form-grid two-columns">\n'
                       '        <label>Sapaan<input type="text" name="greeting" value="{{ '
                       'profile.greeting }}" required></label>\n'
                       '        <label>Nama Lengkap<input type="text" name="full_name" value="{{ '
                       'profile.full_name }}" required></label>\n'
                       '        <label class="full-column">Judul / Profesi<input type="text" '
                       'name="title" value="{{ profile.title }}" required></label>\n'
                       '        <label class="full-column">Tentang Saya<textarea name="about_text" '
                       'rows="6">{{ profile.about_text }}</textarea></label>\n'
                       '    </div>\n'
                       '    <div class="form-section-title"><h2>Foto Profil</h2></div>\n'
                       '    <div class="upload-row">\n'
                       '        <div class="image-preview large-preview">\n'
                       '            <img id="photo-preview" src="{{ profile.photo_url or '
                       'url_for(\'static\', filename=\'images/hero-default.png\') }}" alt="Preview '
                       'foto">\n'
                       '        </div>\n'
                       '        <label class="file-label">Pilih Foto<input type="file" '
                       'name="photo" accept="image/png,image/jpeg,image/webp" '
                       'data-preview-target="#photo-preview"><span><i class="bi '
                       'bi-cloud-arrow-up"></i> Pilih gambar baru</span></label>\n'
                       '    </div>\n'
                       '    <div class="form-section-title"><h2>Kontak & Tautan</h2></div>\n'
                       '    <div class="form-grid two-columns">\n'
                       '        <label>Email<input type="email" name="email" value="{{ '
                       'profile.email }}"></label>\n'
                       '        <label>Nomor Telepon<input type="text" name="phone" value="{{ '
                       'profile.phone }}"></label>\n'
                       '        <label>Lokasi<input type="text" name="location" value="{{ '
                       'profile.location }}"></label>\n'
                       '        <label>LinkedIn<input type="url" name="linkedin_url" value="{{ '
                       'profile.linkedin_url }}" '
                       'placeholder="https://linkedin.com/in/..."></label>\n'
                       '        <label>Instagram<input type="url" name="instagram_url" value="{{ '
                       'profile.instagram_url }}" '
                       'placeholder="https://instagram.com/..."></label>\n'
                       '    </div>\n'
                       '    <div class="form-actions"><button class="admin-button" '
                       'type="submit"><i class="bi bi-check2"></i> Simpan Profil</button></div>\n'
                       '</form>\n'
                       '{% endblock %}\n',
 'admin/projects.html': '{% extends "admin/base_admin.html" %}\n'
                        '{% block title %}Proyek | Admin Jenny{% endblock %}\n'
                        '{% block content %}\n'
                        '<div class="page-heading"><div><span '
                        'class="eyebrow">Karya</span><h1>Proyek</h1></div></div>\n'
                        '<section class="admin-panel form-panel">\n'
                        '    <div class="form-section-title"><h2>Tambah Proyek</h2></div>\n'
                        '    <form method="post" enctype="multipart/form-data" class="form-grid '
                        'two-columns compact-form">\n'
                        '        <input type="hidden" name="csrf_token" value="{{ csrf_token() '
                        '}}">\n'
                        '        <label>Judul Proyek<input type="text" name="title" '
                        'required></label>\n'
                        '        <label>Kategori<input type="text" name="category" value="Web '
                        'Design"></label>\n'
                        '        <label>Teknologi<input type="text" name="technologies" '
                        'placeholder="Flask, TiDB, Cloudinary"></label>\n'
                        '        <label>Urutan<input type="number" name="sort_order" '
                        'value="0"></label>\n'
                        '        <label>URL Proyek<input type="url" name="project_url" '
                        'placeholder="https://..."></label>\n'
                        '        <label>URL GitHub<input type="url" name="github_url" '
                        'placeholder="https://github.com/..."></label>\n'
                        '        <label class="full-column">Deskripsi<textarea name="description" '
                        'rows="4"></textarea></label>\n'
                        '        <label class="full-column">Gambar<input type="file" name="image" '
                        'accept="image/png,image/jpeg,image/webp"></label>\n'
                        '        <label class="checkbox-label"><input type="checkbox" '
                        'name="is_featured" checked> Tampilkan di website</label>\n'
                        '        <div class="form-actions"><button class="admin-button" '
                        'type="submit"><i class="bi bi-plus"></i> Tambahkan</button></div>\n'
                        '    </form>\n'
                        '</section>\n'
                        '<div class="admin-list-grid">\n'
                        '    {% for project in projects %}\n'
                        '    <article class="admin-panel project-admin-card">\n'
                        '        <img src="{{ project.image_url or url_for(\'static\', '
                        'filename=\'images/project-default.png\') }}" alt="{{ project.title }}">\n'
                        '        <div><span>{{ project.category }}</span><h3>{{ project.title '
                        '}}</h3><p>{{ project.description }}</p><small>{{ project.technologies '
                        '}}</small></div>\n'
                        '        <details><summary>Edit Proyek</summary>\n'
                        '            <form method="post" enctype="multipart/form-data" action="{{ '
                        'url_for(\'projects_admin.update\', project_id=project.id) }}" '
                        'class="form-grid two-columns compact-form">\n'
                        '                <input type="hidden" name="csrf_token" value="{{ '
                        'csrf_token() }}">\n'
                        '                <label>Judul<input type="text" name="title" value="{{ '
                        'project.title }}" required></label>\n'
                        '                <label>Kategori<input type="text" name="category" '
                        'value="{{ project.category }}"></label>\n'
                        '                <label>Teknologi<input type="text" name="technologies" '
                        'value="{{ project.technologies }}"></label>\n'
                        '                <label>Urutan<input type="number" name="sort_order" '
                        'value="{{ project.sort_order }}"></label>\n'
                        '                <label>URL Proyek<input type="url" name="project_url" '
                        'value="{{ project.project_url }}"></label>\n'
                        '                <label>URL GitHub<input type="url" name="github_url" '
                        'value="{{ project.github_url }}"></label>\n'
                        '                <label class="full-column">Deskripsi<textarea '
                        'name="description" rows="4">{{ project.description }}</textarea></label>\n'
                        '                <label class="full-column">Ganti gambar<input type="file" '
                        'name="image" accept="image/png,image/jpeg,image/webp"></label>\n'
                        '                <label class="checkbox-label"><input type="checkbox" '
                        'name="is_featured" {{ \'checked\' if project.is_featured else \'\' }}> '
                        'Tampilkan</label>\n'
                        '                <div class="form-actions"><button class="admin-button '
                        'small" type="submit">Simpan</button></div>\n'
                        '            </form>\n'
                        '        </details>\n'
                        '        <form method="post" action="{{ url_for(\'projects_admin.delete\', '
                        'project_id=project.id) }}" data-confirm="Hapus proyek ini?">\n'
                        '            <input type="hidden" name="csrf_token" value="{{ csrf_token() '
                        '}}"><button class="danger-button" type="submit"><i class="bi '
                        'bi-trash"></i> Hapus</button>\n'
                        '        </form>\n'
                        '    </article>\n'
                        '    {% else %}<p class="empty-state">Belum ada proyek.</p>{% endfor %}\n'
                        '</div>\n'
                        '{% endblock %}\n',
 'admin/skills.html': '{% extends "admin/base_admin.html" %}\n'
                      '{% block title %}Keahlian | Admin Jenny{% endblock %}\n'
                      '{% block content %}\n'
                      '<div class="page-heading"><div><span '
                      'class="eyebrow">Konten</span><h1>Keahlian</h1></div></div>\n'
                      '<section class="admin-panel form-panel">\n'
                      '    <div class="form-section-title"><h2>Tambah Keahlian</h2></div>\n'
                      '    <form method="post" class="form-grid four-columns compact-form">\n'
                      '        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">\n'
                      '        <label>Nama<input type="text" name="name" required></label>\n'
                      '        <label>Ikon<input type="text" name="icon" '
                      'value="bi-stars"></label>\n'
                      '        <label>Aksen<select name="accent"><option '
                      'value="pink">Pink</option><option '
                      'value="green">Hijau</option></select></label>\n'
                      '        <label>Urutan<input type="number" name="sort_order" '
                      'value="0"></label>\n'
                      '        <label class="full-column">Deskripsi<textarea name="description" '
                      'rows="3"></textarea></label>\n'
                      '        <label class="checkbox-label"><input type="checkbox" '
                      'name="is_active" checked> Tampilkan di website</label>\n'
                      '        <div class="form-actions"><button class="admin-button" '
                      'type="submit"><i class="bi bi-plus"></i> Tambahkan</button></div>\n'
                      '    </form>\n'
                      '</section>\n'
                      '<div class="admin-list-grid">\n'
                      '    {% for skill in skills %}\n'
                      '    <article class="admin-panel item-card">\n'
                      '        <div class="item-card-heading"><span class="item-icon"><i class="bi '
                      '{{ skill.icon }}"></i></span><div><h3>{{ skill.name }}</h3><p>Urutan {{ '
                      "skill.sort_order }} · {{ 'Aktif' if skill.is_active else 'Nonaktif' "
                      '}}</p></div></div>\n'
                      '        <p>{{ skill.description }}</p>\n'
                      '        <details><summary>Edit Keahlian</summary>\n'
                      '            <form method="post" action="{{ url_for(\'skills_admin.update\', '
                      'skill_id=skill.id) }}" class="form-grid two-columns compact-form">\n'
                      '                <input type="hidden" name="csrf_token" value="{{ '
                      'csrf_token() }}">\n'
                      '                <label>Nama<input type="text" name="name" value="{{ '
                      'skill.name }}" required></label>\n'
                      '                <label>Ikon<input type="text" name="icon" value="{{ '
                      'skill.icon }}"></label>\n'
                      '                <label>Aksen<select name="accent"><option value="pink" {{ '
                      "'selected' if skill.accent == 'pink' else '' }}>Pink</option><option "
                      'value="green" {{ \'selected\' if skill.accent == \'green\' else \'\' '
                      '}}>Hijau</option></select></label>\n'
                      '                <label>Urutan<input type="number" name="sort_order" '
                      'value="{{ skill.sort_order }}"></label>\n'
                      '                <label class="full-column">Deskripsi<textarea '
                      'name="description" rows="3">{{ skill.description }}</textarea></label>\n'
                      '                <label class="checkbox-label"><input type="checkbox" '
                      'name="is_active" {{ \'checked\' if skill.is_active else \'\' }}> '
                      'Tampilkan</label>\n'
                      '                <div class="form-actions"><button class="admin-button '
                      'small" type="submit">Simpan</button></div>\n'
                      '            </form>\n'
                      '        </details>\n'
                      '        <form method="post" action="{{ url_for(\'skills_admin.delete\', '
                      'skill_id=skill.id) }}" data-confirm="Hapus keahlian ini?">\n'
                      '            <input type="hidden" name="csrf_token" value="{{ csrf_token() '
                      '}}"><button class="danger-button" type="submit"><i class="bi bi-trash"></i> '
                      'Hapus</button>\n'
                      '        </form>\n'
                      '    </article>\n'
                      '    {% else %}<p class="empty-state">Belum ada keahlian.</p>{% endfor %}\n'
                      '</div>\n'
                      '{% endblock %}\n',
 'auth/login.html': '<!doctype html>\n'
                    '<html lang="id">\n'
                    '<head>\n'
                    '    <meta charset="utf-8">\n'
                    '    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
                    '    <title>Login Admin | Jenny.</title>\n'
                    '    <link rel="preconnect" href="https://fonts.googleapis.com">\n'
                    '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
                    '    <link '
                    'href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" '
                    'rel="stylesheet">\n'
                    '    <link rel="stylesheet" '
                    'href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">\n'
                    '    <link rel="stylesheet" href="{{ url_for(\'static\', '
                    'filename=\'css/login.css\') }}">\n'
                    '</head>\n'
                    '<body class="login-page">\n'
                    '    <main class="login-card">\n'
                    '        <a class="login-brand" href="{{ url_for(\'main.home\') '
                    '}}">Jenny.</a>\n'
                    '        <span class="login-icon"><i class="bi bi-flower2"></i></span>\n'
                    '        <h1>Masuk ke Dashboard</h1>\n'
                    '        {% with messages = get_flashed_messages(with_categories=true) %}\n'
                    '            {% for category, message in messages %}<div '
                    'class="login-alert">{{ message }}</div>{% endfor %}\n'
                    '        {% endwith %}\n'
                    '        <form method="post">\n'
                    '            <input type="hidden" name="csrf_token" value="{{ csrf_token() '
                    '}}">\n'
                    '            <label>Email\n'
                    '                <span class="input-wrap"><i class="bi bi-envelope"></i><input '
                    'type="email" name="email" placeholder="admin@email.com" required '
                    'autofocus></span>\n'
                    '            </label>\n'
                    '            <label>Password\n'
                    '                <span class="input-wrap"><i class="bi bi-lock"></i><input '
                    'type="password" name="password" id="password" placeholder="Masukkan password" '
                    'required><button type="button" class="password-toggle" aria-label="Tampilkan '
                    'password"><i class="bi bi-eye"></i></button></span>\n'
                    '            </label>\n'
                    '            <label class="remember"><input type="checkbox" name="remember"> '
                    'Ingat saya</label>\n'
                    '            <button class="login-button" type="submit">Masuk <i class="bi '
                    'bi-arrow-right"></i></button>\n'
                    '        </form>\n'
                    '        <a class="back-link" href="{{ url_for(\'main.home\') }}"><i class="bi '
                    'bi-arrow-left"></i> Kembali ke website</a>\n'
                    '    </main>\n'
                    '    <script>\n'
                    "        const toggle = document.querySelector('.password-toggle');\n"
                    "        const password = document.getElementById('password');\n"
                    "        toggle?.addEventListener('click', () => {\n"
                    "            password.type = password.type === 'password' ? 'text' : "
                    "'password';\n"
                    "            toggle.querySelector('i').className = password.type === "
                    "'password' ? 'bi bi-eye' : 'bi bi-eye-slash';\n"
                    '        });\n'
                    '    </script>\n'
                    '</body>\n'
                    '</html>\n',
 'base.html': '<!doctype html>\n'
              '<html lang="id">\n'
              '<head>\n'
              '    <meta charset="utf-8">\n'
              '    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
              '    <meta name="description" content="Website portofolio Jenny Ananda Prasetya">\n'
              '    <title>{% block title %}Jenny. | Portofolio{% endblock %}</title>\n'
              '    <link rel="preconnect" href="https://fonts.googleapis.com">\n'
              '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
              '    <link '
              'href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700;800&display=swap" '
              'rel="stylesheet">\n'
              '    <link rel="stylesheet" '
              'href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">\n'
              '    <link rel="stylesheet" href="{{ url_for(\'static\', filename=\'css/main.css\') '
              '}}">\n'
              '    <link rel="stylesheet" href="{{ url_for(\'static\', '
              'filename=\'css/responsive.css\') }}">\n'
              '    {% block head %}{% endblock %}\n'
              '</head>\n'
              '<body>\n'
              '    <header class="site-header" id="top">\n'
              '        <nav class="navbar container" aria-label="Navigasi utama">\n'
              '           <a href="/admin/login"class="brand"title="Login Admin"aria-label="Masuk '
              'ke halaman login admin">Jenny.</a>\n'
              '\n'
              '            <div class="nav-actions">\n'
              '                <a href="{{ url_for(\'main.home\') }}#home" '
              'class="nav-link">Home</a>\n'
              '\n'
              '                <div class="flower-menu">\n'
              '                    <button\n'
              '                        class="flower-menu-toggle"\n'
              '                        type="button"\n'
              '                        aria-expanded="false"\n'
              '                        aria-controls="flower-menu-dropdown"\n'
              '                        aria-label="Buka menu navigasi"\n'
              '                    >\n'
              '                        <i class="bi bi-flower2" aria-hidden="true"></i>\n'
              '                    </button>\n'
              '\n'
              '                    <div class="flower-dropdown" id="flower-menu-dropdown">\n'
              '                        <a href="{{ url_for(\'main.home\') }}#about">\n'
              '                            <i class="bi bi-person-heart" aria-hidden="true"></i>\n'
              '                            <span>Tentang</span>\n'
              '                        </a>\n'
              '                        <a href="{{ url_for(\'main.home\') }}#skills">\n'
              '                            <i class="bi bi-stars" aria-hidden="true"></i>\n'
              '                            <span>Keahlian</span>\n'
              '                        </a>\n'
              '                        <a href="{{ url_for(\'main.home\') }}#experience">\n'
              '                            <i class="bi bi-briefcase" aria-hidden="true"></i>\n'
              '                            <span>Pengalaman</span>\n'
              '                        </a>\n'
              '                        <a href="{{ url_for(\'main.home\') }}#projects">\n'
              '                            <i class="bi bi-grid" aria-hidden="true"></i>\n'
              '                            <span>Proyek Saya</span>\n'
              '                        </a>\n'
              '                        <a href="{{ url_for(\'main.home\') }}#contact">\n'
              '                            <i class="bi bi-envelope-heart" '
              'aria-hidden="true"></i>\n'
              '                            <span>Kontak</span>\n'
              '                        </a>\n'
              '                    </div>\n'
              '                </div>\n'
              '            </div>\n'
              '        </nav>\n'
              '    </header>\n'
              '\n'
              '    <div class="flash-stack container" aria-live="polite">\n'
              '        {% with messages = get_flashed_messages(with_categories=true) %}\n'
              '            {% for category, message in messages %}\n'
              '                <div class="flash flash-{{ category }}">\n'
              '                    <span>{{ message }}</span>\n'
              '                    <button type="button" class="flash-close" '
              'aria-label="Tutup">&times;</button>\n'
              '                </div>\n'
              '            {% endfor %}\n'
              '        {% endwith %}\n'
              '    </div>\n'
              '\n'
              '    <main>{% block content %}{% endblock %}</main>\n'
              '\n'
              '    <footer class="site-footer">\n'
              '    <div class="container footer-inner">\n'
              '        <p> &copy; {{ current_year }} Jenny. Dibuat dengan perhatian pada setiap '
              'detail.</p>\n'
              '    </div>\n'
              '</footer>\n'
              '    <script src="{{ url_for(\'static\', filename=\'js/main.js\') }}" '
              'defer></script>\n'
              '    {% block scripts %}{% endblock %}\n'
              '</body>\n'
              '</html>\n',
 'public/about.html': '<section class="about section-floral" id="about">\n'
                      '    <div class="container narrow-section reveal">\n'
                      '        <span class="section-kicker">Tentang</span>\n'
                      '        <h2 class="section-heading">Tentang Saya</h2>\n'
                      '        <p class="section-subtitle">\n'
                      '            {{ profile.about_text if profile and profile.about_text else '
                      "'Saya menyukai proses mengubah kebutuhan dan ide menjadi pengalaman digital "
                      "yang rapi, mudah digunakan, dan memiliki karakter visual yang kuat.' }}\n"
                      '        </p>\n'
                      '        <div class="about-meta">\n'
                      '            {% if profile and profile.location %}<span><i class="bi '
                      'bi-geo-alt"></i> {{ profile.location }}</span>{% endif %}\n'
                      '            {% if profile and profile.email %}<span><i class="bi '
                      'bi-envelope"></i> {{ profile.email }}</span>{% endif %}\n'
                      '        </div>\n'
                      '        {% if profile and profile.resume_url %}\n'
                      '            <a class="button button-outline" href="{{ profile.resume_url '
                      '}}" target="_blank" rel="noopener">Unduh Resume <i class="bi '
                      'bi-download"></i></a>\n'
                      '        {% endif %}\n'
                      '    </div>\n'
                      '</section>\n',
 'public/contact.html': '<section class="contact-section section-floral" id="contact">\n'
                        '    <div class="container">\n'
                        '        <div class="section-intro reveal">\n'
                        '            <span class="section-kicker">Kontak</span>\n'
                        '            <h2 class="section-heading">Hubungi Saya</h2>\n'
                        '            <p class="section-subtitle">Punya ide, proyek, atau ingin '
                        'berdiskusi? Kirimkan pesan melalui form berikut.</p>\n'
                        '        </div>\n'
                        '        <div class="contact-layout">\n'
                        '            <div class="contact-info reveal">\n'
                        '                <h3>Mari membuat sesuatu yang bermakna.</h3>\n'
                        '                <p>Saya terbuka untuk diskusi proyek akademik, '
                        'pengembangan website, desain antarmuka, dan kolaborasi kreatif.</p>\n'
                        '                <div class="contact-list">\n'
                        '                    {% if profile and profile.email %}<a href="mailto:{{ '
                        'profile.email }}"><i class="bi bi-envelope"></i><span>{{ profile.email '
                        '}}</span></a>{% endif %}\n'
                        '                    {% if profile and profile.phone %}<a href="tel:{{ '
                        'profile.phone }}"><i class="bi bi-telephone"></i><span>{{ profile.phone '
                        '}}</span></a>{% endif %}\n'
                        '                    {% if profile and profile.location %}<span><i '
                        'class="bi bi-geo-alt"></i><span>{{ profile.location }}</span></span>{% '
                        'endif %}\n'
                        '                </div>\n'
                        '                <div class="social-links">\n'
                        '                    {% if profile and profile.github_url %}<a href="{{ '
                        'profile.github_url }}" aria-label="GitHub" target="_blank" '
                        'rel="noopener"><i class="bi bi-github"></i></a>{% endif %}\n'
                        '                    {% if profile and profile.linkedin_url %}<a href="{{ '
                        'profile.linkedin_url }}" aria-label="LinkedIn" target="_blank" '
                        'rel="noopener"><i class="bi bi-linkedin"></i></a>{% endif %}\n'
                        '                    {% if profile and profile.instagram_url %}<a href="{{ '
                        'profile.instagram_url }}" aria-label="Instagram" target="_blank" '
                        'rel="noopener"><i class="bi bi-instagram"></i></a>{% endif %}\n'
                        '                </div>\n'
                        '            </div>\n'
                        '            <form class="contact-form reveal" action="{{ '
                        'url_for(\'contact.send_message\') }}" method="post" id="contact-form">\n'
                        '                <input type="hidden" name="csrf_token" value="{{ '
                        'csrf_token() }}">\n'
                        '                <label>Nama<input type="text" name="name" '
                        'placeholder="Nama Anda" maxlength="120" required></label>\n'
                        '                <label>Email<input type="email" name="email" '
                        'placeholder="Email Anda" maxlength="190" required></label>\n'
                        '                <label>Subjek<input type="text" name="subject" '
                        'placeholder="Subjek Anda" maxlength="200" required></label>\n'
                        '                <label>Pesan<textarea name="message" placeholder="Pesan '
                        'Anda" rows="6" maxlength="5000" required></textarea></label>\n'
                        '                <button class="button button-primary contact-submit" '
                        'type="submit">Kirim Pesan <i class="bi bi-send-fill"></i></button>\n'
                        '            </form>\n'
                        '        </div>\n'
                        '    </div>\n'
                        '</section>\n',
 'public/experience.html': '<section class="experience-section section-floral" id="experience">\n'
                           '    <div class="container">\n'
                           '        <div class="section-intro reveal">\n'
                           '            <span class="section-kicker">Perjalanan</span>\n'
                           '            <h2 class="section-heading">Pengalaman</h2>\n'
                           '            <p class="section-subtitle">Perjalanan belajar dan '
                           'berkembang melalui proyek, organisasi, serta pengalaman akademik.</p>\n'
                           '        </div>\n'
                           '        <div class="timeline">\n'
                           '            {% for experience in experiences %}\n'
                           '                <article class="timeline-item {{ \'timeline-left\' if '
                           'loop.index is odd else \'timeline-right\' }} reveal">\n'
                           '                    <div class="timeline-content">\n'
                           '                        <span class="year-pill">{{ '
                           'experience.start_year }} — {{ experience.end_year }}</span>\n'
                           '                        <h3>{{ experience.company }}</h3>\n'
                           '                        <h4>{{ experience.role }}</h4>\n'
                           '                        <p>{{ experience.description }}</p>\n'
                           '                    </div>\n'
                           '                    <div class="timeline-marker"><i class="bi {{ '
                           'experience.icon }}"></i></div>\n'
                           '                    <div class="timeline-image">\n'
                           '                        {% if experience.image_url %}\n'
                           '                            <img src="{{ experience.image_url }}" '
                           'alt="{{ experience.company }}">\n'
                           '                        {% else %}\n'
                           '                            <div class="experience-placeholder">\n'
                           '                                <i class="bi bi-laptop"></i>\n'
                           '                                <span>{{ experience.company }}</span>\n'
                           '                            </div>\n'
                           '                        {% endif %}\n'
                           '                    </div>\n'
                           '                </article>\n'
                           '            {% else %}\n'
                           '                <p class="empty-public">Pengalaman akan segera '
                           'ditambahkan.</p>\n'
                           '            {% endfor %}\n'
                           '        </div>\n'
                           '    </div>\n'
                           '</section>\n',
 'public/home.html': '{% extends "base.html" %}\n'
                     '{% block title %}Jenny. | Portofolio{% endblock %}\n'
                     '{% block content %}\n'
                     '<section id="home" class="hero section-floral">\n'
                     '    <div class="container hero-grid">\n'
                     '        <div class="hero-copy reveal">\n'
                     '            <p class="hero-greeting">{{ profile.greeting if profile else '
                     "'Halo! Saya Jenny' }}</p>\n"
                     "            <h1>{{ profile.full_name if profile else 'Jenny Ananda Prasetya' "
                     '}}</h1>\n'
                     '            <p class="hero-title">{{ profile.title if profile else '
                     "'Mahasiswa S1 Sistem Informasi Universitas Kristen Satya Wacana' }}</p>\n"
                     '            <a class="button button-primary" href="#projects">Lihat Proyek '
                     'Saya</a>\n'
                     '        </div>\n'
                     '        <div class="hero-visual reveal" aria-label="Foto profil Jenny">\n'
                     '            <div class="hero-glow"></div>\n'
                     '            {% if profile and profile.photo_url %}\n'
                     '                <img src="{{ profile.photo_url }}" alt="Foto {{ '
                     'profile.full_name }}" class="hero-photo">\n'
                     '            {% else %}\n'
                     '                <img src="{{ url_for(\'static\', '
                     'filename=\'images/hero-default.png\') }}" alt="Ilustrasi ruang kerja '
                     'portofolio" class="hero-photo hero-photo-composite">\n'
                     '            {% endif %}\n'
                     '            <i class="bi bi-flower1 hero-decoration flower-top"></i>\n'
                     '            <i class="bi bi-heart-fill hero-decoration flower-bottom"></i>\n'
                     '        </div>\n'
                     '    </div>\n'
                     '</section>\n'
                     '\n'
                     '{% include "public/about.html" %}\n'
                     '{% include "public/skills.html" %}\n'
                     '{% include "public/experience.html" %}\n'
                     '{% include "public/projects.html" %}\n'
                     '{% include "public/contact.html" %}\n'
                     '{% endblock %}\n'
                     '\n'
                     '{% block scripts %}<script src="{{ url_for(\'static\', '
                     'filename=\'js/contact.js\') }}" defer></script>{% endblock %}\n',
 'public/projects.html': '<section class="projects-section" id="projects">\n'
                         '    <div class="container">\n'
                         '        <div class="section-intro reveal">\n'
                         '            <span class="section-kicker">Karya</span>\n'
                         '            <h2 class="section-heading">Proyek Saya</h2>\n'
                         '            <p class="section-subtitle">Beberapa proyek yang '
                         'merepresentasikan proses analisis, desain, dan pengembangan yang saya '
                         'kerjakan.</p>\n'
                         '        </div>\n'
                         '        <div class="projects-grid">\n'
                         '            {% for project in projects %}\n'
                         '                <article class="project-card reveal">\n'
                         '                    <div class="project-image-wrap">\n'
                         '                        <img src="{{ project.image_url or '
                         'url_for(\'static\', filename=\'images/project-default.png\') }}" alt="{{ '
                         'project.title }}">\n'
                         '                        <span class="project-category">{{ '
                         'project.category }}</span>\n'
                         '                    </div>\n'
                         '                    <div class="project-body">\n'
                         '                        <h3>{{ project.title }}</h3>\n'
                         '                        <p>{{ project.description }}</p>\n'
                         '                        {% if project.technologies %}\n'
                         '                            <div class="project-tech">\n'
                         '                                {% for tech in '
                         "project.technologies.split(',') %}<span>{{ tech.strip() }}</span>{% "
                         'endfor %}\n'
                         '                            </div>\n'
                         '                        {% endif %}\n'
                         '                        <div class="project-links">\n'
                         '                            {% if project.project_url %}<a href="{{ '
                         'project.project_url }}" target="_blank" rel="noopener">Lihat Proyek <i '
                         'class="bi bi-arrow-up-right"></i></a>{% endif %}\n'
                         '                            {% if project.github_url %}<a href="{{ '
                         'project.github_url }}" target="_blank" rel="noopener"><i class="bi '
                         'bi-github"></i> GitHub</a>{% endif %}\n'
                         '                        </div>\n'
                         '                    </div>\n'
                         '                </article>\n'
                         '            {% else %}\n'
                         '                <p class="empty-public">Proyek akan segera '
                         'ditambahkan.</p>\n'
                         '            {% endfor %}\n'
                         '        </div>\n'
                         '    </div>\n'
                         '</section>\n',
 'public/skills.html': '<section class="skills-section" id="skills">\n'
                       '    <div class="container">\n'
                       '        <div class="section-intro reveal">\n'
                       '            <span class="section-kicker">Skill</span>\n'
                       '            <h2 class="section-heading dark-heading">Keahlian</h2>\n'
                       '            <span class="heading-line"></span>\n'
                       '        </div>\n'
                       '        <div class="skills-grid">\n'
                       '            {% for skill in skills %}\n'
                       '                <article class="skill-card reveal">\n'
                       '                    <div class="skill-icon {{ \'green\' if skill.accent == '
                       '\'green\' else \'pink\' }}">\n'
                       '                        <i class="bi {{ skill.icon }}"></i>\n'
                       '                    </div>\n'
                       '                    <h3>{{ skill.name }}</h3>\n'
                       '                    <p>{{ skill.description }}</p>\n'
                       '                </article>\n'
                       '            {% else %}\n'
                       '                <p class="empty-public">Keahlian akan segera '
                       'ditambahkan.</p>\n'
                       '            {% endfor %}\n'
                       '        </div>\n'
                       '    </div>\n'
                       '</section>\n'}
